#!/bin/bash
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  RANN Agent — Vercel Deployment Guide                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "PREREQUISITES:"
echo "  1. Node.js 18+ installed"
echo "  2. Vercel CLI: npm i -g vercel"
echo "  3. Logged in:  vercel login"
echo ""
echo "DEPLOY STEPS:"
echo ""
echo "  1. Navigate to project:"
echo "     cd /home/userland/rann-agent"
echo ""
echo "  2. Deploy to Vercel (preview):"
echo "     vercel"
echo ""
echo "  3. Deploy to production:"
echo "     vercel --prod"
echo ""
echo "  4. Set environment variables (optional):"
echo "     vercel env add OPENAI_API_KEY"
echo "     vercel env add GROQ_API_KEY"
echo ""
echo "ENDPOINTS AFTER DEPLOY:"
echo "  GET  /api/providers     — list all providers"
echo "  GET  /api/config        — default provider & model"
echo "  GET  /api/status        — system status"
echo "  POST /api/chat          — streaming chat (SSE)"
echo "  POST /api/clear         — clear session"
echo ""
echo "FRONTEND ROUTES:"
echo "  /             — index.html (main chat UI)"
echo "  /dashboard    — dashboard.html"
echo ""
echo "FRONTEND API CALLS (update your HTML to use these):"
echo ""
echo "  // Fetch providers"
echo "  const res = await fetch('/api/providers');"
echo "  const providers = await res.json();"
echo ""
echo "  // Streaming chat"
echo "  const response = await fetch('/api/chat', {"
echo "    method: 'POST',"
echo "    headers: { 'Content-Type': 'application/json' },"
echo "    body: JSON.stringify({"
echo "      message: 'Hello',"
echo "      history: [],"
echo "      provider: 'groq',"
echo "      model: 'llama-3.1-70b-versatile',"
echo "      api_key: 'YOUR_API_KEY'"
echo "    })"
echo "  });"
echo "  // response is SSE stream"
echo "  // Parse: for await (const line of response.body) { ... }"
echo ""
echo "NOTE: API keys are sent client-side and stored in localStorage."
echo "      For production, consider moving key storage to Vercel KV"
echo "      or server-side environment variables."
echo ""